/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import com.sun.javafx.scene.control.skin.ComboBoxPopupControl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import static javaapplication9.Server.din4;

import javax.swing.JComboBox;
//import static javaapplication9.Server.din;
//import static javaapplication9.Server.dout;

/**
 *
 * @author Ankit Raj
 */
public class Client extends javax.swing.JFrame {

   static Socket s,s2,s3;
   static DataInputStream din,din2,din3,din4;
   static DataOutputStream dout,dout2,dout3,dout4;
    String selectedLanguage="cpp";
    public Client() {
        initComponents();
        clientThread1.start();
        clientThread2.start();
        SelectedLang.start();
        buildOutput.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        jLabel1.setText("Client");

        TextArea1.setEditable(false);
        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane2.setViewportView(TextArea1);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C++", "Java", "C" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("RUN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        output.setColumns(20);
        output.setRows(5);
        jScrollPane3.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     Thread clientThread1 = new Thread(new Runnable() {
       @Override
       public void run() {
        String messageIn="";
        try{
            s=new Socket("192.168.0.4",5002);
            din=new DataInputStream(s.getInputStream());
            dout=new DataOutputStream(s.getOutputStream());
            while(true)
           {
               messageIn=din.readUTF();
               textArea.setText( messageIn );
           }
            
        }
        catch(Exception e){
            System.out.println("Exception occured:1" + e);
        }
       }
   });
     Thread clientThread2 = new Thread(new Runnable() {
       @Override
       public void run() {
        String messageIn="";
        try{
            s2=new Socket("192.168.0.4",5005);
            din2=new DataInputStream(s2.getInputStream());
            dout2=new DataOutputStream(s2.getOutputStream());
            while(true)
           {
               messageIn=din2.readUTF();
               TextArea1.setText( messageIn );
           }
            
        }
        catch(Exception e){
            System.out.println("Exception occured:2" + e);
        }
       }
   });
     Thread SelectedLang = new Thread(new Runnable() {
       @Override
       public void run() {
        String messageIn="";
        try{
            s3=new Socket("192.168.0.4",5011);
            din3=new DataInputStream(s3.getInputStream());
            dout3=new DataOutputStream(s3.getOutputStream());
            while(true)
           {
               messageIn=din3.readUTF();
               System.out.println(messageIn);
              if(messageIn.equals("C++"))
                    jComboBox1.setSelectedIndex(0);
              else if(messageIn.equals("Java"))
                    jComboBox1.setSelectedIndex(1);
              else if(messageIn.equals("C"))
                    jComboBox1.setSelectedIndex(2);
           }
            
        }
        catch(Exception e){
            System.out.println("Exception occured:2" + e);
        }
       }
   });
     
     
      Thread buildOutput=new Thread(new Runnable() {
        @Override
        public void run() {
            Socket s4=null;
            String outputMessage=null;
            while(true){
                try{
                    
                    s4=new Socket("192.168.0.4", 5020);
                    System.out.println("Connection established in output");
                    din4=new DataInputStream(s4.getInputStream());
                    dout4=new DataOutputStream(s4.getOutputStream());
                    while(true){
                        outputMessage=din4.readUTF();
                        output.setText(outputMessage);
                    }
                    
                }
                catch(Exception e){
                    try{
                        s4.close();
                        
                    }
                    catch(IOException e1){
                        System.out.println("Exception e1");
                        e1.printStackTrace();
                    }
                    System.out.println("Exception 21");
                    e.printStackTrace();
                    
                }
            }
            
        }
    });
      
      
      
      
    private void textAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyPressed
  
    }//GEN-LAST:event_textAreaKeyPressed

    private void textAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyReleased

             String messageOut="";
        try{
            messageOut=textArea.getText();
            //System.out.println(messageOut);
            dout.writeUTF(messageOut);
            dout.flush();
        }
        catch(Exception e){
            System.out.println("Exception occured :"+ e);
        }  
    }//GEN-LAST:event_textAreaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String messageOut="",msout="";
        try{
            messageOut=TextArea1.getText();
            msout = jTextField1.getText();
            messageOut = messageOut + "\n" + "Interviwee : " + msout;
            TextArea1.setText(messageOut);
            System.out.println(messageOut);
            dout2.writeUTF(messageOut);
            dout2.flush(); 
            jTextField1.setText("");
        }
        catch(Exception e){
            System.out.println("Exception occured :"+ e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      /*JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String selectedLang = (String) combo.getSelectedItem();
        try{
           // System.out.println(selectedLang);
    
        dout3.writeUTF(selectedLang);
        dout3.flush();
          
        }
        catch(Exception e){
            System.out.println("Exception occured :" + e);
        }*/
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
 /*JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String selectedLang = (String) combo.getSelectedItem();
        try{
           // System.out.println(selectedLang);
    
        dout3.writeUTF(selectedLang);
        dout3.flush();
          
        }
        catch(Exception e){
            System.out.println("Exception occured :" + e);
        }*/
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String selectedLang = (String) combo.getSelectedItem();
        try{
           // System.out.println(selectedLang);
           selectedLanguage=selectedLang;
        dout3.writeUTF(selectedLang);
        dout3.flush();
          
        }
        catch(Exception e){
            System.out.println("Exception occured :" + e);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println(selectedLanguage);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea TextArea1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea output;
    private static javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
